# Generated by Django 6.0.2 on 2026-09-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='acronyme',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
